name: Build Test

on:
  pull_request:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build a docker image
        run: |
          docker build .
